version:    "0003--25-Sep-2022"
copyright:  "2022"
author:     "Raspati Mahatma Kurnia Dharmatmaja"
title:      "OS222: Operating Systems 2022-2"
githublink: "https://github.com/tommyraspati/os222"
myloglink:  "/TXT/mylog.txt"
encoding:   UTF-8
markdown:   kramdown
input:      GFM
hard_wrap:  false
github:     [metadata]
